### ISSUE TITLE
Not a spring boot application

### ISSUE THREAD

**Issue by hemantsonu20** [irfanjs/unitdbamqpservice#1]
https://stackoverflow.com/questions/50608331/properties-are-not-working-in-spring-boot-based-java-application/50608477?noredirect=1#comment88228401_50608477

This repository is not a spring boot application, pom.xml , Application class missing.

Regarding DbUnitHelper class
If it is annotated with @Component, you don't need to create another instance, spring creates a singleton class for you, you just need to autowire this class (similar to enviroment) class and use it, if you manually create this class, and @Autowire dependency will not be injected and it will be null.

If you want to create a simple spring boot project go to https://start.spring.io/. it will give you a basic structure of project

**Comment by irfanjs** [comment]
thanks. it is fixed now. used the @Autowire annotation and used the spring singleton class
